### ISSUE TITLE
&user, &gconfg, &uconfig Not Responding

### ISSUE THREAD

**Issue by Feathers8** [Nightorn/Aldebaran#31]
**Describe the bug**
Doing `&user`, `&gconfig list`, or `&uconfig list` simply produces no output.

**To Reproduce**
1. Do `&user`.
2. Notice how Aldebaran doesn't respond.

**Expected behavior**
Showing info like join date, account-creation date, etc.

**Aldebaran details:**
 - Version 1.11.0

**Comment by Willard21** [comment]
&user
```js
(node:16484) UnhandledPromiseRejectionWarning: TypeError: message.guild.members.get is not a function
    at /home/willard/Aldebaran/src/commands/general/user.js:18:41
```
&uconfig list
```js
TypeError: message.guild.members.get is not a function
    at UconfigCommand.run (/home/willard/Aldebaran/src/commands/settings/uconfig.js:31:27)
```
&gconfig list
```js
TypeError: message.guild.members.get is not a function
    at GconfigCommand.run (/home/willard/Aldebaran/src/commands/settings/gconfig.js:29:27)
```
